import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const require=createRequire(path.join(root,'frontend/package.json'));
const {chromium,request,expect}=require('@playwright/test');
const api=await request.newContext({baseURL:'http://127.0.0.1:5173'});
// Respect production throttling; retry only explicit 429 responses, never duplicate successful writes.
const post = async (url, options) => {
  let response = await api.post(url, options);
  if (response.status() === 429) {
    const seconds = Math.min(65, Math.max(1, Number(response.headers()['retry-after']) || 60));
    console.log('Rate limit reached in regression; waiting', seconds, 'seconds.');
    await new Promise(resolve => setTimeout(resolve, seconds * 1000 + 250));
    response = await api.post(url, options);
  }
  return response;
};
const accounts=JSON.parse(fs.readFileSync(path.join(root,'.local/test-accounts.json'),'utf8'));
const login=async role=>{const r=await post('/api/auth/login',{data:{email:accounts[role].email,matKhau:accounts[role].password}});assert.equal(r.status(),200);return r.json();};
const admin=await login('admin'),user=await login('user');
const auth={Authorization:'Bearer '+user.token},adminAuth={Authorization:'Bearer '+admin.token};
const tag='feedback-'+Date.now();
const fixture=action=>execFileSync('dotnet',['run','--no-build','--project',path.join(root,'tests/AdminSmoke'),'--',path.join(root,'backend'),'--feedback-fixtures',action,tag],{cwd:root,encoding:'utf8'});
const f=JSON.parse(fixture('create').trim());
const checks=[],errors=[];let browser;
const check=(name,value)=>{assert.ok(value,name);checks.push(name);};
const targets=[['tours',f.tour],['hotels',f.hotel],['destinations',f.destination]];
const base=(kind,id)=>`/api/feedback/${kind}/${id}`;
const read=async(kind,id)=>{const r=await api.get(base(kind,id));assert.equal(r.status(),200,await r.text());return r.json();};
try {
  for(const [kind,id] of targets) {
    const url=base(kind,id);
    const initial=await read(kind,id);
    check(`${kind}: public empty feedback excludes unverified legacy`,initial.summary.count===0&&initial.comments.length===0);
    check(`${kind}: anonymous comment blocked`,(await post(url+'/comments',{data:{content:'guest'}})).status()===401);
    check(`${kind}: anonymous rating blocked`,(await post(url+'/reviews',{data:{stars:5}})).status()===401);
    check(`${kind}: eligibility requires login`,(await api.get(url+'/eligibility')).status()===401);
    check(`${kind}: pending booking cannot rate`,(await post(url+'/reviews',{headers:auth,data:{stars:5,maNguoiDung:f.admin,maDatTourXacMinh:f.tourOrder}})).status()===403);
    const comment=await post(url+'/comments',{headers:auth,data:{content:tag+' '+kind,maNguoiDung:f.admin}});
    check(`${kind}: logged-in account comments before experience`,comment.status()===201);
    const listed=await read(kind,id);
    check(`${kind}: public comments identify JWT author only`,listed.comments[0].author===user.user.hoTen&&!('maNguoiDung' in listed.comments[0])&&!('email' in listed.comments[0]));
    check(`${kind}: blank comment rejected`,(await post(url+'/comments',{headers:auth,data:{content:'   '}})).status()===400);
    check(`${kind}: long comment rejected`,(await post(url+'/comments',{headers:auth,data:{content:'a'.repeat(2001)}})).status()===400);
  }
  const tourUrl=base('tours',f.tour);
  check('Admin legacy create cannot bypass experience',(await post('/api/danhgia',{headers:adminAuth,data:{maNguoiDung:f.admin,maTour:f.tour,soSao:5}})).status()===409);
  check('Cannot forge experience using another account',(await post(tourUrl+'/reviews',{headers:adminAuth,data:{stars:5,maNguoiDung:f.owner}})).status()===403);
  await api.put(`/api/dattour/${f.tourOrder}`,{headers:adminAuth,data:{trangThai:'Confirmed'}});
  check('Confirmed tour is not completed',(await post(tourUrl+'/reviews',{headers:auth,data:{stars:5}})).status()===403);
  assert.equal((await api.put(`/api/dattour/${f.tourOrder}`,{headers:adminAuth,data:{trangThai:'Completed'}})).status(),204);
  for(const state of ['Confirmed','CheckedIn','CheckedOut']) {
    const r=await api.put(`/api/datphong/${f.roomOrder}`,{headers:adminAuth,data:{trangThai:state}});assert(r.ok(),await r.text());
    if(state==='CheckedIn')check('Checked-in hotel is not completed',(await post(base('hotels',f.hotel)+'/reviews',{headers:auth,data:{stars:5}})).status()===403);
  }
  fixture('future');
  for(const [kind,id] of targets)check(`${kind}: future completion date blocks rating`,(await post(base(kind,id)+'/reviews',{headers:auth,data:{stars:5}})).status()===403);
  fixture('past');
  for(const [kind,id] of targets)check(`${kind}: completed past booking allows rating`,(await (await api.get(base(kind,id)+'/eligibility',{headers:auth})).json()).canReview===true);
  check('Stars outside 1–5 rejected',(await post(tourUrl+'/reviews',{headers:auth,data:{stars:6}})).status()===400);
  const race=await Promise.all([4,5].map(stars=>post(tourUrl+'/reviews',{headers:auth,data:{stars,content:tag+' verified'}})));
  check('Concurrent duplicate rating limited to one',race.filter(r=>r.status()===201).length===1&&race.filter(r=>r.status()===409).length===1);
  const reviewId=(await race.find(r=>r.status()===201).json()).id;
  check('Own completed review blocks resubmission',(await (await api.get(tourUrl+'/eligibility',{headers:auth})).json()).alreadyReviewed===true);
  check('Customer cannot moderate',(await api.put('/api/danhgia/'+reviewId,{headers:auth,data:{trangThai:false}})).status()===403);
  check('Admin cannot rewrite stars',(await api.put('/api/danhgia/'+reviewId,{headers:adminAuth,data:{soSao:1}})).status()===400);
  const before=await read('tours',f.tour);
  check('Public average uses verified reviews only',before.summary.count===1&&before.summary.average===before.reviews[0].stars);
  assert.equal((await api.put('/api/danhgia/'+reviewId,{headers:adminAuth,data:{trangThai:false}})).status(),204);
  check('Hidden review removed from count and average',(await read('tours',f.tour)).summary.count===0);
  check('Cannot resubmit hidden review',(await post(tourUrl+'/reviews',{headers:auth,data:{stars:5}})).status()===409);
  await api.put('/api/danhgia/'+reviewId,{headers:adminAuth,data:{trangThai:true}});
  const catalog=await (await api.get('/api/tour/'+f.tour)).json();
  check('Catalog uses same verified summary',catalog.soLuotDanhGia===1&&catalog.diemDanhGia===before.summary.average);
  const commentId=(await read('tours',f.tour)).comments[0].id;
  const adminComment=await (await api.get('/api/binhluan/'+commentId,{headers:adminAuth})).json();
  check('Admin comment DTO matches UI and preserves boolean status',adminComment.maBinhLuan===commentId&&adminComment.trangThai===true);
  check('Comment moderation admin-only',(await api.put('/api/binhluan/'+commentId,{headers:auth,data:{trangThai:false}})).status()===403);
  assert.equal((await api.put('/api/binhluan/'+commentId,{headers:adminAuth,data:{trangThai:false}})).status(),204);
  check('Hidden comment is not public',(await read('tours',f.tour)).comments.length===0);
  await api.put('/api/binhluan/'+commentId,{headers:adminAuth,data:{trangThai:true}});
  check('Unknown target gives 404',(await api.get(base('tours',2147483647))).status()===404);
  check('Invalid kind gives 404',(await api.get(base('invalid',f.tour))).status()===404);
  check('Invalid page gives 400',(await api.get(tourUrl+'?commentPage=0')).status()===400);
  for(let i=0;i<11;i++)assert.equal((await post(tourUrl+'/comments',{headers:auth,data:{content:tag+' paging '+i}})).status(),201);
  check('Public comments paginated', (await read('tours',f.tour)).comments.length===10&&(await (await api.get(tourUrl+'?commentPage=2')).json()).comments.length===2);
  const duplicate=await Promise.all([1,2].map(()=>post(tourUrl+'/comments',{headers:auth,data:{content:tag+' identical'}})));
  check('Duplicate comment submission blocked',duplicate.filter(r=>r.status()===201).length===1&&duplicate.filter(r=>r.status()===409).length===1);
  browser=await chromium.launch();
  for(const [width,kind,id] of [[1440,'hotels',f.hotel],[390,'destinations',f.destination]]) {
    const ctx=await browser.newContext({baseURL:'http://127.0.0.1:5173',viewport:{width,height:1000},reducedMotion:'reduce'});
    const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));
    await page.goto(`/${kind}/${id}`);await expect(page.getByRole('link',{name:'Đăng nhập để bình luận'})).toBeVisible();
    await expect(page.getByText(tag+' '+kind,{exact:true})).toBeVisible();
    await page.getByRole('link',{name:'Đăng nhập để bình luận'}).click();
    await page.getByLabel('Email',{exact:true}).fill(accounts.user.email);
    await page.locator('input[autocomplete="current-password"]').fill(accounts.user.password);
    await page.getByRole('button',{name:'Đăng nhập',exact:true}).click();
    await expect(page).toHaveURL(new RegExp(`/${kind}/${id}#feedback`));
    await page.getByRole('radio',{name:'4 sao',exact:true}).check();
    await page.getByLabel('Nhận xét về trải nghiệm (không bắt buộc)').fill(tag+' browser rating');
    await page.getByRole('button',{name:'Gửi đánh giá',exact:true}).click();
    await expect(page.getByText('Đã lưu đánh giá của bạn.',{exact:true})).toBeVisible();
    await expect(page.getByText('4/5 sao từ 1 đánh giá đã xác minh',{exact:true})).toBeVisible();
    await page.getByLabel('Bình luận của bạn',{exact:true}).fill('<img src=x onerror=alert(1)> '+tag+' '+width);
    await page.getByRole('button',{name:'Gửi bình luận',exact:true}).click();
    await expect(page.getByText('Đã gửi bình luận.',{exact:true})).toBeVisible();
    await page.reload();await expect(page.getByText('<img src=x onerror=alert(1)> '+tag+' '+width,{exact:true})).toBeVisible();
    check(`${width}: plain text comments cannot inject HTML`,await page.locator('.feedback-content img').count()===0);
    assert(await page.locator('main').evaluate(el=>el.scrollWidth<=el.clientWidth+2));
    await page.locator('#feedback').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(root,`.local/feedback-${width}.png`)});
    checks.push(`${width}: guest reads, login returns, eligible rating and comment persist, responsive`);
    await ctx.close();
  }
  const adminPage=await browser.newPage({baseURL:'http://127.0.0.1:5173',viewport:{width:1440,height:1000}});
  await adminPage.addInitScript(s=>localStorage.setItem('tripmate_auth',JSON.stringify(s)),admin);
  adminPage.on('dialog',d=>d.accept());
  await adminPage.goto('/admin/comments?id='+commentId);
  await adminPage.getByRole('button',{name:'Xem chi tiết #'+commentId,exact:true}).click();
  await adminPage.getByRole('button',{name:'Ẩn bình luận',exact:true}).click();
  await expect(adminPage.getByRole('status')).toContainText('Đã cập nhật trạng thái bình luận');
  checks.push('Admin comment moderation UI works');
  await adminPage.goto(`/tours/${f.tour}`);
  await expect(adminPage.getByText('Chỉ chấm sao sau khi đơn tour của bạn được xác nhận Đã hoàn thành và chuyến đi đã kết thúc.',{exact:true})).toBeVisible();
  await expect(adminPage.getByRole('button',{name:'Gửi đánh giá',exact:true})).toHaveCount(0);
  await adminPage.getByLabel('Bình luận của bạn',{exact:true}).fill(tag+' no experience UI');
  await adminPage.getByRole('button',{name:'Gửi bình luận',exact:true}).click();
  await expect(adminPage.getByText('Đã gửi bình luận.',{exact:true})).toBeVisible();
  checks.push('Logged-in account without experience can comment but cannot rate in UI');
  await adminPage.goto('/tours');
  await expect(adminPage.locator('.catalog-grid a').first()).toHaveAttribute('href',`/tours/${f.tour}`);
  checks.push('Catalog defaults to highest verified rating first');
  assert.deepEqual(errors,[]);console.log(JSON.stringify({checks,errors},null,2));
} finally {await browser?.close();await api.dispose();console.log(fixture('cleanup').trim());}
