import { test, expect, type Page } from '@playwright/test';

const env=process.env;
test.beforeEach(async({page})=>{
  if(!env.E2E_TAG) throw new Error('Run through tests/AdminSmoke --browser to create and clean disposable fixtures.');
  // Province provider is the only stub: keep browser tests independent of third-party availability.
  await page.route('https://provinces.open-api.vn/**',route=>route.fulfill({json:[{code:22,name:'Tỉnh Quảng Ninh'},{code:48,name:'Thành phố Đà Nẵng'}]}));
  page.on('dialog',dialog=>dialog.accept());
});
async function login(page:Page,admin=false) {
  await page.goto('/login');
  await page.getByLabel('Email',{exact:true}).fill((admin?env.E2E_ADMIN_EMAIL:env.E2E_EMAIL)!);
  await page.locator('input[autocomplete="current-password"]').fill(env.E2E_PASSWORD!);
  await page.getByRole('button',{name:'Đăng nhập',exact:true}).click();
  await expect(page).toHaveURL(admin?/\/admin$/:/\/account$/);
}
test('catalog filters update in place, pagination and mobile layout',async({page},testInfo)=>{
  await page.setViewportSize({width:390,height:844});
  await page.goto('/tours');
  await expect(page.locator('.catalog-card').first()).toBeVisible();
  await page.getByRole('button',{name:'Trang sau',exact:true}).click();
  await expect(page).toHaveURL(/page=2/);
  const curtain=await page.locator('.route-curtain').elementHandle();
  await page.getByLabel('Tỉnh / thành phố',{exact:true}).selectOption('Quảng Ninh');
  await expect(page).not.toHaveURL(/page=2/);
  expect(await curtain!.evaluate(node=>node===document.querySelector('.route-curtain'))).toBe(true);
  await page.getByLabel('Giá đến (đ)',{exact:true}).fill('1000000');
  await page.getByLabel('Số ngày',{exact:true}).selectOption('2');
  await expect(page.getByRole('link',{name:env.E2E_TAG!,exact:true})).toBeVisible();
  await page.getByLabel('Giá từ (đ)',{exact:true}).fill('2000000');
  await expect(page.getByRole('alert')).toContainText('Giá đến');
  await page.getByRole('button',{name:'Xóa bộ lọc',exact:true}).first().click();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  await page.screenshot({path:testInfo.outputPath('catalog-mobile.png'),fullPage:true,animations:'disabled'});
});
test('customer books tour; admin confirms and cancels; history retained',async({page,browser})=>{
  await login(page);
  await page.goto('/tours?keyword='+encodeURIComponent(env.E2E_TAG!));
  await page.getByRole('link',{name:env.E2E_TAG!,exact:true}).click();
  await page.getByRole('link',{name:'Đặt tour',exact:true}).click();
  await page.getByLabel('Số khách',{exact:true}).fill('2');
  const created=page.waitForResponse(r=>r.url().endsWith('/api/account/bookings/tours')&&r.request().method()==='POST');
  await page.getByRole('button',{name:'Xác nhận yêu cầu đặt chỗ'}).click();
  const response=await created; expect(response.status()).toBe(201); const order=await response.json();
  await expect(page.getByText('YÊU CẦU ĐÃ ĐƯỢC LƯU')).toBeVisible();
  await page.getByRole('link',{name:'Xem đơn đặt của tôi'}).click();
  await expect(page.locator('.booking-record').filter({hasText:env.E2E_TAG})).toContainText('Chờ xác nhận');
  const context=await browser.newContext({baseURL:'http://127.0.0.1:5173'});const admin=await context.newPage();
  admin.on('dialog',d=>d.accept()); await login(admin,true);
  await admin.getByRole('link',{name:'Đơn tour',exact:true}).click();
  const row=admin.getByTestId('order-'+order.id);
  await row.getByRole('button',{name:'Đã xác nhận',exact:true}).click();
  await expect(row.getByRole('button',{name:'Hoàn thành',exact:true})).toBeVisible();
  await row.getByRole('button',{name:'Đã hủy',exact:true}).click();
  await expect(row).toContainText('Đã kết thúc');
  await page.reload();
  await expect(page.locator('.booking-record').filter({hasText:env.E2E_TAG})).toContainText('Đã hủy');
  await context.close();
});
test('room booking flows through UI and account',async({page})=>{
  await login(page);
  await page.goto('/hotels/'+env.E2E_HOTEL);
  await page.getByRole('link',{name:'Đặt phòng',exact:true}).click();
  const start=new Date(); start.setDate(start.getDate()+45);
  const end=new Date(start); end.setDate(end.getDate()+2);
  await page.getByLabel('Ngày nhận phòng',{exact:true}).fill(start.toISOString().slice(0,10));
  await page.getByLabel('Ngày trả phòng',{exact:true}).fill(end.toISOString().slice(0,10));
  await page.getByLabel('Số khách',{exact:true}).fill('2');
  await page.getByRole('button',{name:'Xác nhận yêu cầu đặt chỗ'}).click();
  await expect(page.getByText('YÊU CẦU ĐÃ ĐƯỢC LƯU')).toBeVisible();
  await page.getByRole('link',{name:'Xem đơn đặt của tôi'}).click();
  await page.getByRole('button',{name:'Phòng đã đặt',exact:true}).click();
  await expect(page.locator('.booking-record').filter({hasText:env.E2E_TAG})).toContainText('Chờ xác nhận');
});
test('admin creates destination, uploads image, archives, views dashboard and audit',async({page},testInfo)=>{
  await login(page,true);
  await expect(page.getByRole('heading',{name:'Hoạt động kinh doanh'})).toBeVisible();
  await expect(page.getByText('Tiền đã thu',{exact:true})).toBeVisible();
  await page.screenshot({path:testInfo.outputPath('admin-dashboard.png'),fullPage:true,animations:'disabled'});
  await page.getByRole('link',{name:'Địa điểm du lịch'}).first().click();
  await page.getByRole('button',{name:'+ Thêm mới'}).click();
  await page.getByLabel('Tên địa điểm *',{exact:true}).fill(env.E2E_TAG+' destination');
  await page.getByLabel('Loại địa điểm',{exact:true}).selectOption({index:1});
  await page.getByRole('button',{name:'Lưu thông tin',exact:true}).click();
  await expect(page.getByText('Đã lưu thành công.',{exact:true})).toBeVisible();
  await page.getByLabel('Chọn nhiều ảnh từ máy tính').setInputFiles(env.E2E_IMAGE!);
  await page.getByRole('button',{name:'Tải ảnh lên',exact:true}).click();
  await expect(page.getByText('Đã tải 1 ảnh thành công.',{exact:true})).toBeVisible();
  await expect(page.locator('.admin-image-card img')).toBeVisible();
  await page.getByLabel('Tìm trong danh sách').fill(env.E2E_TAG!);
  await page.getByRole('button',{name:'Ngừng bán / Ẩn',exact:true}).click();
  await expect(page.getByText('Đã ngừng bán / ẩn; lịch sử được giữ nguyên.',{exact:true})).toBeVisible();
  await expect(page.locator('tbody')).toContainText('Đã khóa / ẩn');
  await page.getByRole('link',{name:'Nhật ký quản trị',exact:true}).click();
  await expect(page.locator('tbody')).toContainText('DiaDiem');
  await expect(page.locator('tbody')).toContainText('Thành công');
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
test('customer saves itinerary, invites a member, and revokes shared access',async({page,browser},testInfo)=>{
  await login(page);
  await page.getByRole('link',{name:'Tạo lịch trình mới',exact:true}).click();
  await page.getByLabel('Tên chuyến đi',{exact:true}).fill(env.E2E_TAG+' trip');
  await page.getByLabel('Khởi hành từ',{exact:true}).fill('Hà Nội');
  await page.getByLabel('Điểm đến tại Việt Nam',{exact:true}).fill('ha long');
  await page.getByRole('group',{name:'Gợi ý điểm đến tại việt nam',exact:true}).getByRole('button',{name:'Vịnh Hạ Long',exact:true}).click();
  await page.getByLabel('Các điểm đến và hoạt động',{exact:true}).fill('Buổi sáng: tập trung lúc 8 giờ');
  await page.getByRole('button',{name:'Thêm Vịnh Hạ Long',exact:true}).click();
  await expect(page.getByRole('button',{name:'Đã thêm Vịnh Hạ Long',exact:true})).toBeDisabled();
  await expect(page.getByLabel('Các điểm đến và hoạt động',{exact:true})).toHaveValue('Buổi sáng: tập trung lúc 8 giờ\n• Tham quan Vịnh Hạ Long');
  await page.getByLabel('Tiêu đề',{exact:true}).fill('Khám phá vịnh');
  await page.getByRole('button',{name:'Thêm một ngày',exact:true}).click();
  await expect(page.getByLabel('Các điểm đến và hoạt động',{exact:true}).nth(1)).toHaveValue('');
  await page.getByLabel('Điểm đến tại Việt Nam',{exact:true}).fill('hue');
  await expect(page.getByRole('button',{name:'Thêm Vịnh Hạ Long',exact:true})).toHaveCount(0);
  await page.locator('fieldset').nth(1).getByRole('button',{name:'Thêm Đại Nội Huế',exact:true}).click();
  await expect(page.getByLabel('Tiêu đề',{exact:true}).first()).toHaveValue('Khám phá vịnh');
  await expect(page.getByLabel('Các điểm đến và hoạt động',{exact:true}).first()).toHaveValue('Buổi sáng: tập trung lúc 8 giờ\n• Tham quan Vịnh Hạ Long');
  await page.getByLabel('Điểm đến tại Việt Nam',{exact:true}).fill('Không có địa danh này');
  await expect(page.getByRole('status')).toContainText('Chưa có địa điểm phù hợp');
  await page.getByLabel('Điểm đến tại Việt Nam',{exact:true}).fill('Huế');
  await page.getByLabel('Tiêu đề',{exact:true}).nth(1).fill('Trở về');
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  await page.screenshot({path:testInfo.outputPath('planner-recommendations-mobile.png'),fullPage:true,animations:'disabled'});
  await page.getByRole('button',{name:'Lưu lịch trình',exact:true}).click();
  await expect(page).toHaveURL(/\/account\?tab=trips&trip=\d+$/);
  await page.getByRole('button',{name:'Lịch trình của tôi',exact:true}).click();
  await page.getByRole('link',{name:'Xem lịch trình: '+env.E2E_TAG+' trip',exact:true}).click();
  const trip=page.locator('article').filter({hasText:env.E2E_TAG+' trip'});
  await expect(trip).toContainText('Ngày 2: Trở về');
  await expect(trip).toContainText('Tham quan Vịnh Hạ Long');
  await expect(trip).toContainText('Tham quan Đại Nội Huế');
  await trip.getByRole('button',{name:'Quản lý thành viên',exact:true}).click();
  await trip.getByLabel('Email thành viên',{exact:true}).fill(env.E2E_ADMIN_EMAIL!);
  await trip.getByRole('button',{name:'Gửi lời mời',exact:true}).click();
  await expect(page.getByText('Đã gửi lời mời. Người được mời xem và phản hồi trong trang tài khoản.',{exact:true})).toBeVisible();
  await trip.getByRole('button',{name:'Quản lý thành viên',exact:true}).click();
  await expect(trip.locator('.member-list')).toContainText('Chờ phản hồi');
  const context=await browser.newContext({baseURL:'http://127.0.0.1:5173'});
  try {
    const recipient=await context.newPage();
    await login(recipient,true);
    await recipient.goto('/account');
    const invitation=recipient.locator('.trip-invitations article').filter({hasText:env.E2E_TAG+' trip'});
    await invitation.getByRole('button',{name:'Chấp nhận',exact:true}).click();
    await recipient.getByRole('link',{name:'Xem lịch trình: '+env.E2E_TAG+' trip',exact:true}).click();
    const shared=recipient.locator('article.user-panel').filter({hasText:env.E2E_TAG+' trip'});
    await expect(shared).toContainText('Chuyến đi bạn đã tham gia');
    await expect(shared.getByRole('button',{name:'Quản lý thành viên',exact:true})).toHaveCount(0);
    await expect(shared).toContainText('Tham quan Đại Nội Huế');
    await page.reload();
    await page.getByRole('button',{name:'Lịch trình của tôi',exact:true}).click();
    await page.getByRole('link',{name:'Xem lịch trình: '+env.E2E_TAG+' trip',exact:true}).click();
    await trip.getByRole('button',{name:'Quản lý thành viên',exact:true}).click();
    await expect(trip.locator('.member-list')).toContainText('Đã tham gia');
    await page.screenshot({path:testInfo.outputPath('trip-members-mobile.png'),fullPage:true,animations:'disabled'});
    await trip.getByRole('button',{name:'Gỡ thành viên',exact:true}).click();
    await trip.getByRole('button',{name:'Xác nhận gỡ',exact:true}).click();
    await expect(trip).toContainText('Chưa mời thành viên nào');
    await recipient.reload();
    await recipient.getByRole('button',{name:'Lịch trình của tôi',exact:true}).click();
    await expect(recipient.getByRole('heading',{name:env.E2E_TAG+' trip',exact:true})).toHaveCount(0);
  } finally { await context.close(); }
});

test('planner recommendations can retry while keeping manual notes',async({page})=>{
  await login(page);
  await page.route('**/api/diadiem',route=>route.fulfill({status:503,json:{message:'Temporary test outage'}}));
  await page.goto('/planner');
  await page.getByLabel('Điểm đến tại Việt Nam',{exact:true}).fill('Quảng Ninh');
  await page.getByLabel('Các điểm đến và hoạt động',{exact:true}).fill('Ghi chú tự viết');
  await expect(page.getByRole('button',{name:'Tải lại gợi ý',exact:true})).toBeVisible();
  await page.unroute('**/api/diadiem');
  await page.getByRole('button',{name:'Tải lại gợi ý',exact:true}).click();
  await expect(page.getByRole('button',{name:'Thêm Vịnh Hạ Long',exact:true})).toBeVisible();
  await expect(page.getByLabel('Các điểm đến và hoạt động',{exact:true})).toHaveValue('Ghi chú tự viết');
});
test('guest login redirect and catalog error retry',async({page})=>{
  await page.goto('/admin/tour-orders');
  await expect(page).toHaveURL(/\/login\?returnTo=/);
  await page.route('**/api/tour',r=>r.fulfill({status:503,json:{message:'Dịch vụ thử tạm thời không khả dụng'}}));
  await page.goto('/tours');
  await expect(page.getByRole('alert')).toBeVisible();
  await page.unroute('**/api/tour');
  await page.getByRole('button',{name:'Thử lại',exact:true}).click();
  await expect(page.locator('.catalog-card').first()).toBeVisible();
});
