import { useRef, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { api, errorMessage, money } from '../../lib/api';
import { useResource } from '../User/catalog';
import { Pager } from './Operations';
import FormDialog from '../../components/FormDialog';
import ValidatedForm from '../../components/ValidatedForm';
import { reportFormError } from '../../components/form-validation';
type Payment={maThanhToan:number;loaiDon:string;maDatTour?:number;maDatPhong?:number;soTien:number;phuongThuc:string;maGiaoDich?:string;trangThai:string;ngayThanhToan?:string};
type Order={maDatTour?:number;maDatPhong?:number;maNguoiDung:number;tongTien:number;trangThai:string};
const statuses:Record<string,string>={ChoThanhToan:'Chờ xác nhận',ThanhCong:'Đã thu tiền',ThatBai:'Thất bại',DaHoanTien:'Đã hoàn tiền (lịch sử)'};
const methods:Record<string,string>={TienMat:'Tiền mặt',ChuyenKhoan:'Chuyển khoản',VNPay:'VNPay',Momo:'MoMo',ZaloPay:'ZaloPay'};
export default function Payments(){
  const payments=useResource<Payment[]>('/thanhtoan'),tours=useResource<Order[]>('/dattour'),rooms=useResource<Order[]>('/datphong');
  const [form,setForm]=useState({loaiDon:'DatTour',order:'',soTien:'',phuongThuc:'TienMat',maGiaoDich:''});
  const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[status,setStatus]=useState(''),[page,setPage]=useState(1);
  const lock=useRef(false);
  const editor=useRef<HTMLFormElement>(null);
  const source=form.loaiDon==='DatTour'?tours:rooms;
  const orderId=(o:Order)=>form.loaiDon==='DatTour'?o.maDatTour:o.maDatPhong;
  const selected=source.data?.find(o=>String(orderId(o))===form.order);
  const used=(payments.data||[]).filter(p=>p.loaiDon===form.loaiDon&&String(p.maDatTour||p.maDatPhong)===form.order&&['ChoThanhToan','ThanhCong'].includes(p.trangThai)).reduce((s,p)=>s+p.soTien,0);
  const remaining=selected?Math.max(0,selected.tongTien-used):0;
  const rows=(payments.data||[]).filter(p=>!status||p.trangThai===status),pages=Math.max(1,Math.ceil(rows.length/10)),current=Math.min(page,pages);
  async function create(e:FormEvent){
    e.preventDefault();if(lock.current)return;setError('');setNotice('');
    if(!selected||Number(form.soTien)<=0||Number(form.soTien)>remaining)return setError('Chọn đơn và số tiền dương, không vượt phần còn lại.');
    lock.current=true;setBusy(true);
    try{await api.post('/thanhtoan',{loaiDon:form.loaiDon,maDatTour:form.loaiDon==='DatTour'?Number(form.order):null,maDatPhong:form.loaiDon==='DatPhong'?Number(form.order):null,soTien:Number(form.soTien),phuongThuc:form.phuongThuc,maGiaoDich:form.maGiaoDich.trim()||null});setOpen(false);setForm({...form,soTien:'',maGiaoDich:''});setNotice('Đã tạo giao dịch chờ xác nhận. Chỉ xác nhận đã thu khi có chứng từ thực tế.');payments.reload();}catch(e){setError(errorMessage(e));reportFormError(editor.current,e,{soTien:['số tiền','phần còn lại'],order:['đơn','maDatTour','maDatPhong'],maGiaoDich:['mã giao dịch']});}finally{lock.current=false;setBusy(false);}
  }
  async function change(payment:Payment,next:string){
    if(lock.current||!window.confirm(next==='ThanhCong'?`Xác nhận đã thực nhận ${money(payment.soTien)} cho giao dịch #${payment.maThanhToan}? Thao tác không thay thế chuyển tiền thực tế.`:`Đánh dấu giao dịch #${payment.maThanhToan} thất bại?`))return;
    lock.current=true;setBusy(true);setError('');setNotice('');
    try{await api.put(`/thanhtoan/${payment.maThanhToan}`,{trangThai:next});setNotice('Đã ghi nhận kết quả giao dịch.');payments.reload();}catch(e){setError(errorMessage(e));}finally{lock.current=false;setBusy(false);}
  }
  return <section className="admin-panel"><div className="admin-section-title"><h1>Thanh toán</h1><button disabled={busy} onClick={()=>setOpen(!open)}>{open?'Đóng biểu mẫu':'Ghi nhận thanh toán'}</button></div><p>Đây là sổ ghi nhận thủ công, không phải cổng thanh toán trực tuyến. Giao dịch đã kết thúc không sửa/xóa; ứng dụng chưa có quy trình hoàn tiền.</p>{notice&&<p className="admin-notice" role="status">{notice}</p>}{error&&<p className="admin-error" role="alert">{error}</p>}
    {open&&<FormDialog title="Ghi nhận thanh toán" onClose={()=>{setOpen(false);setError('');}} busy={busy}><ValidatedForm formRef={editor} onSubmit={create}><fieldset disabled={busy} className="admin-form-grid"><label>Loại đơn<select name="loaiDon" value={form.loaiDon} onChange={e=>setForm({...form,loaiDon:e.target.value,order:'',soTien:''})}><option value="DatTour">Đơn tour</option><option value="DatPhong">Đơn phòng</option></select></label><label>Đơn cần thanh toán<select name="order" required value={form.order} disabled={source.loading||!!source.error} onChange={e=>setForm({...form,order:e.target.value,soTien:''})}><option value="">{source.loading?'Đang tải…':'Chọn đơn'}</option>{source.data?.filter(o=>o.trangThai!=='Cancelled').map(o=><option key={orderId(o)} value={orderId(o)}>#{orderId(o)} · Khách #{o.maNguoiDung} · {money(o.tongTien)}</option>)}</select></label><label>Số tiền (đ)<input name="soTien" required type="number" min="0.01" step="0.01" max={remaining} value={form.soTien} onChange={e=>setForm({...form,soTien:e.target.value})}/></label><label>Phương thức<select name="phuongThuc" value={form.phuongThuc} onChange={e=>setForm({...form,phuongThuc:e.target.value})}>{Object.entries(methods).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Mã giao dịch / chứng từ (nếu có)<input name="maGiaoDich" maxLength={150} value={form.maGiaoDich} onChange={e=>setForm({...form,maGiaoDich:e.target.value})}/></label></fieldset>{source.error&&<p role="alert">{source.error} <button type="button" onClick={source.reload}>Tải lại đơn</button></p>}{selected&&<p>Phần còn lại sau các giao dịch chờ và đã thu: <strong>{money(remaining)}</strong>.</p>}{error&&<p role="alert" className="admin-error">{error}</p>}<button disabled={busy||source.loading||!!source.error||payments.loading||!!payments.error}>{busy?'Đang lưu…':'Tạo giao dịch chờ xác nhận'}</button></ValidatedForm></FormDialog>}
    <div className="admin-filter-row"><label>Lọc trạng thái<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">Tất cả</option>{Object.entries(statuses).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><button className="secondary" onClick={payments.reload}>Làm mới</button></div>{payments.loading&&<p role="status">Đang tải thanh toán…</p>}{payments.error&&<p role="alert">{payments.error}</p>}{!payments.loading&&!payments.error&&<><div className="admin-table-wrap" role="region" tabIndex={0} aria-label="Bảng dữ liệu, cuộn ngang để xem thêm"><table><thead><tr><th>Mã / đơn</th><th>Số tiền</th><th>Phương thức / chứng từ</th><th>Trạng thái</th><th>Xử lý</th></tr></thead><tbody>{rows.slice((current-1)*10,current*10).map(p=><tr key={p.maThanhToan}><td>#{p.maThanhToan}<small><Link to={`/admin/${p.loaiDon==='DatTour'?'tour-orders':'room-orders'}?id=${p.maDatTour||p.maDatPhong}`}>{p.loaiDon==='DatTour'?'Đơn tour':'Đơn phòng'} #{p.maDatTour||p.maDatPhong}</Link></small></td><td>{money(p.soTien)}</td><td>{methods[p.phuongThuc]||p.phuongThuc}<small>{p.maGiaoDich||'Không có mã giao dịch'}</small></td><td>{statuses[p.trangThai]||p.trangThai}<small>{p.ngayThanhToan?.replace('T',' ')}</small></td><td>{p.trangThai==='ChoThanhToan'?<div className="admin-actions"><button disabled={busy} onClick={()=>change(p,'ThanhCong')}>Xác nhận đã thu</button><button className="secondary" disabled={busy} onClick={()=>change(p,'ThatBai')}>Thất bại</button></div>:<span>Chỉ xem</span>}</td></tr>)}</tbody></table></div>{!rows.length&&<p>Chưa có giao dịch phù hợp.</p>}<Pager current={current} pages={pages} change={setPage}/></>}</section>;
}
