export type Row = Record<string, unknown>;
export type Field = { key: string; label: string; type?: string; required?: boolean; min?: number; max?: number; maxLength?: number; createOnly?: boolean; options?: [string, string][]; lookup?: string; id?: string; name?: string };
export type Module = { title: string; endpoint: string; id: string; name: string; owner?: string; fields: Field[]; defaults: Row; noDelete?: boolean };
const f = (key: string, label: string, type = 'text', required = false, min?: number): Field => ({ key, label, type, required, min });
const status = f('trangThai', 'Đang hoạt động', 'checkbox');
const address = [f('diaChi', 'Địa chỉ'), f('tinhThanh', 'Tỉnh / thành phố', 'province'), f('quanHuyen', 'Quận / huyện'), f('phuongXa', 'Phường / xã')];
const description = f('moTa', 'Mô tả', 'textarea');
export const modules: Record<string, Module> = {
  rooms: { title:'Loại phòng',endpoint:'loaiphong',id:'maLoaiPhong',name:'tenLoaiPhong',owner:'LoaiPhong',defaults:{trangThai:true,sucChua:2,soLuongPhong:1,giaMoiDem:0},fields:[{key:'maKhachSan',label:'Khách sạn',lookup:'khachsan',id:'maKhachSan',name:'tenKhachSan',required:true},f('tenLoaiPhong','Tên loại phòng','text',true),description,f('sucChua','Sức chứa / phòng','number',true,1),f('soLuongPhong','Số phòng','number',true,1),f('giaMoiDem','Giá mỗi đêm (đ)','number',true,0),status]},
  expenses: {title:'Chi phí chuyến đi',endpoint:'chiphi',id:'maChiPhi',name:'tenChiPhi',noDelete:true,defaults:{loaiChiPhi:'Khac',soTien:0},fields:[{key:'maChuyenDi',label:'Chuyến đi',lookup:'chuyendi',id:'maChuyenDi',name:'tenChuyenDi',required:true,createOnly:true},{key:'maNguoiDung',label:'Người chi (không bắt buộc)',lookup:'nguoidung',id:'maNguoiDung',name:'hoTen',createOnly:true},f('tenChiPhi','Tên khoản chi','text',true),{key:'loaiChiPhi',label:'Nhóm chi phí',options:[['DiChuyen','Di chuyển'],['AnUong','Ăn uống'],['KhachSan','Khách sạn'],['VeThamQuan','Vé tham quan'],['MuaSam','Mua sắm'],['Khac','Khác']]},f('soTien','Số tiền (đ)','number',true,0),f('ngayChi','Ngày chi','date',true),f('ghiChu','Ghi chú','textarea')]},
  coupons: { title:'Mã giảm giá',endpoint:'magiamgia',id:'maCode',name:'code',noDelete:true,defaults:{loaiGiam:'PhanTram',giaTriGiam:10,donHangToiThieu:0,soLuong:0,trangThai:true,ngayBatDau:'',ngayKetThuc:''},fields:[{...f('code','Mã giảm giá','text',true),maxLength:50,createOnly:true},{...description,maxLength:255},{key:'loaiGiam',label:'Cách giảm',createOnly:true,options:[['PhanTram','Phần trăm'],['SoTien','Số tiền cố định']]},f('giaTriGiam','Giá trị giảm','number',true,1),f('giamToiDa','Giảm tối đa (đ, bỏ trống nếu không giới hạn)','number',false,0),f('donHangToiThieu','Đơn tối thiểu (đ)','number',true,0),f('soLuong','Số lượt (0 = không giới hạn)','number',true,0),f('ngayBatDau','Hiệu lực từ','datetime-local',true),f('ngayKetThuc','Hiệu lực đến','datetime-local',true),status]},
  destinations: { title: 'Địa điểm du lịch', endpoint: 'diadiem', id: 'maDiaDiem', name: 'tenDiaDiem', owner: 'DiaDiem', defaults: { maLoai: '', trangThai: true, thoiGianThamQuan: 60, giaVe: 0, giaVeMin: 0, giaVeMax: 0 }, fields: [f('tenDiaDiem', 'Tên địa điểm', 'text', true), { key: 'maLoai', label: 'Loại địa điểm', type: 'number', required: true, lookup: 'loaidiadiem', id: 'maLoai', name: 'tenLoai' }, description, ...address, f('giaVe', 'Giá vé (đ)', 'number', true, 0), f('giaVeMin', 'Giá vé thấp nhất', 'number', true, 0), f('giaVeMax', 'Giá vé cao nhất', 'number', true, 0), f('thoiGianThamQuan', 'Thời gian tham quan (phút)', 'number', true, 1), f('gioMoCua', 'Giờ mở cửa', 'time'), f('gioDongCua', 'Giờ đóng cửa', 'time'), { ...f('viDo', 'Vĩ độ', 'number'), min: -90, max: 90 }, { ...f('kinhDo', 'Kinh độ', 'number'), min: -180, max: 180 }, status] },
  tours: { title: 'Tour du lịch', endpoint: 'tour', id: 'maTour', name: 'tenTour', owner: 'Tour', defaults: { trangThai: 'Draft', soNgay: 1, soDem: 0, giaTour: 0, giaTourMin: 0, giaTourMax: 0, soNguoiToiDa: 20, soNguoiToiThieu: 1 }, fields: [f('tenTour', 'Tên tour', 'text', true), description, f('diemKhoiHanh', 'Điểm khởi hành', 'text', true), f('diemDen', 'Điểm đến', 'text', true), f('soNgay', 'Số ngày', 'number', true, 1), f('soDem', 'Số đêm', 'number', true, 0), f('giaTour', 'Giá tour / người (đ)', 'number', true, 0), f('soNguoiToiThieu', 'Số khách tối thiểu (cả hai bằng 0 nếu chưa xác nhận)', 'number', true, 0), f('soNguoiToiDa', 'Số khách tối đa (cả hai bằng 0 nếu chưa xác nhận)', 'number', true, 0), { key: 'trangThai', label: 'Trạng thái hiển thị', options: [['Draft','Bản nháp'],['Active','Hiển thị; đặt theo lịch khởi hành'],['Inactive','Ngừng bán']] }] },
  hotels: { title: 'Khách sạn', endpoint: 'khachsan', id: 'maKhachSan', name: 'tenKhachSan', owner: 'KhachSan', defaults: { trangThai: true, loaiLuuTru: 'Hotel', giaPhongMin: 0, giaPhongMax: 0 }, fields: [f('tenKhachSan','Tên khách sạn','text',true), { key:'loaiLuuTru', label:'Loại lưu trú', options: ['Hotel','Homestay','Resort','Hostel','Villa'].map(v => [v,v]) }, description, ...address, f('soDienThoai','Số điện thoại'), status] },
  restaurants: { title: 'Nhà hàng', endpoint: 'nhahang', id: 'maNhaHang', name: 'tenNhaHang', owner: 'NhaHang', defaults: { trangThai: true, giaMin: 0, giaMax: 0 }, fields: [f('tenNhaHang','Tên nhà hàng','text',true), description, ...address, f('giaMin','Chi phí thấp nhất (đ)','number',true,0), f('giaMax','Chi phí cao nhất (đ)','number',true,0), f('gioMoCua','Giờ mở cửa','time'), f('gioDongCua','Giờ đóng cửa','time'), f('soDienThoai','Số điện thoại'), status] },
  categories: { title: 'Loại địa điểm', endpoint: 'loaidiadiem', id: 'maLoai', name: 'tenLoai', defaults: { trangThai: true }, fields: [f('tenLoai','Tên loại','text',true), description, status] },
  users: { title: 'Tài khoản', endpoint: 'nguoidung', id: 'maNguoiDung', name: 'hoTen', noDelete: true, defaults: { maVaiTro: 2, trangThai: true }, fields: [f('hoTen','Họ và tên','text',true), f('email','Email','email',true), f('matKhau','Mật khẩu khởi tạo','password',true), f('soDienThoai','Số điện thoại'), { key:'maVaiTro', label:'Vai trò', type:'number', options:[['1','Quản trị viên'],['2','Khách hàng']] }, status] },
  activities: { title: 'Lịch trình từng ngày', endpoint:'tourchitiet', id:'maTourChiTiet', name:'ghiChu', defaults: { ngayThu:1, thuTu:1, loaiDiaDiem:'DiaDiem', chiPhi:0 }, fields: [f('ngayThu','Ngày thứ','number',true,1), f('thuTu','Thứ tự trong ngày','number',true,1), { key:'loaiDiaDiem', label:'Loại hoạt động', options:[['DiaDiem','Tham quan'],['NhaHang','Ăn uống'],['KhachSan','Nghỉ ngơi']] }, { key:'maDiaDiem', label:'Địa điểm', type:'number', lookup:'diadiem', id:'maDiaDiem', name:'tenDiaDiem', required:true }, { key:'maNhaHang', label:'Nhà hàng', type:'number', lookup:'nhahang', id:'maNhaHang', name:'tenNhaHang', required:true }, { key:'maKhachSan', label:'Khách sạn', type:'number', lookup:'khachsan', id:'maKhachSan', name:'tenKhachSan', required:true }, f('thoiGianBatDau','Giờ bắt đầu','time'), f('thoiGianKetThuc','Giờ kết thúc','time'), f('chiPhi','Chi phí tham khảo (đ)','number',true,0), f('ghiChu','Mô tả hoạt động (tối đa 500 ký tự)','textarea',true)] },
  departures: { title:'Ngày khởi hành', endpoint:'tourkhoihanh', id:'maKhoiHanh', name:'ngayKhoiHanh', defaults:{ soChoToiDa:20, soChoDaDat:0, giaApDung:0, trangThai:'OpenForBooking' }, fields:[f('ngayKhoiHanh','Ngày khởi hành','date',true), f('soChoToiDa','Tổng số chỗ','number',true,1), f('giaApDung','Giá áp dụng / người (đ)','number',true,0), { key:'trangThai',label:'Trạng thái',options:[['OpenForBooking','Mở đặt chỗ'],['FullyBooked','Hết chỗ'],['Cancelled','Đã hủy'],['Completed','Hoàn thành']] }] },
};
